### PR TITLE
Fix misc distro related issues

### PR DESCRIPTION
**Pull request by Mystro256**
These issues were found while attempting to package for Fedora

### CODE REVIEW

**Comment by Maxzor** [comment]
This is better than my patches :) https://salsa.debian.org/rocm-team/rocm-compilersupport/-/commit/14c95327cfd97603c0dbae0454edeebbdf916e51

**Comment by Maxzor** [comment]
@Mystro256 Do you understand why for quite each package there are a config, a version, and a target exports?

**Comment by Mystro256** [comment]
> This is better than my patches :) https://salsa.debian.org/rocm-team/rocm-compilersupport/-/commit/14c95327cfd97603c0dbae0454edeebbdf916e51 wish I had found it earlier

I landed the patch in amd-stg-open internally. I'm not sure how long it takes before it's mirrored to github :)

> @Mystro256 Do you understand why for quite each package there are a config, a version, and a target exports? Couldn't there be one single export?

What do you mean by "each package"? Each ROCm package?

**Comment by Mystro256** [comment]
Changes landed in amd-stg-open, closing

**Pull request closed without merging**
